### ISSUE TITLE
ModuleStore::loadFromFile() is not working for relative path

### ISSUE THREAD

**Issue by DineshDevaraj** [markabrahams/node-net-snmp#153]
ModuleStore::loadFromFile() is not working for relative path

**# code** 

```
let snmp = require("net-snmp")
let mibStore = snmp.createModuleStore()

mibStore.loadFromFile("./UCD-SNMP-MIB.mib")

let moduleNames = mibStore.getModuleNames()
console.log("Module name : ", moduleNames)

let providers = mibStore.getProvidersForModule(moduleNames[0])
console.log("Providers : ", providers)

```

**# error**

```
root@c8c1c6a106c2:~/programs/nodejs# node ucd-mib.js
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/root/programs/nodejs/node_modules/net-snmp/lib/./UCD-SNMP-MIB.mib'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Import (/root/programs/nodejs/node_modules/net-snmp/lib/mib.js:134:100)
    at ModuleStore.loadFromFile (/root/programs/nodejs/node_modules/net-snmp/index.js:3064:14)
    at Object.<anonymous> (/root/programs/nodejs/ucd-mib.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
root@c8c1c6a106c2:~/programs/nodejs#

```

**Comment by markabrahams** [comment]
Hi @DineshDevaraj - I've fixed this now in master and published the fix in version 3.0.5 of the npm.

**Comment by DineshDevaraj** [comment]
Hi @markabrahams, Thanks !

**Comment by markabrahams** [comment]
Hi @DineshDevaraj - that's not correct as of version 3.0.5.  The implementation now allows you to specify absolute or relative paths to read MIBs from anywhere.  There are built-in "base" required MIBs included as part of the library, and these are in ./node_modules/net-snmp/lib/mibs (see documentation in `snmp.createModuleStore()` for a list of these "base" MIBs).  But user-supplied MIBs can be read from anywhere.
