### ISSUE TITLE
catch parse value error

### ISSUE THREAD

**Issue by entcor** [markabrahams/node-net-snmp#170]
Hellow 

I have really many devices.
And request on one device generate next error:

RangeError: Integer too long '5'
    at readUint (/server/node_modules/net-snmp/index.js:223:10)
    at readVarbinds (/server/node_modules/net-snmp/index.js:286:12)
    at new GetResponsePdu (/server/node_modules/net-snmp/index.js:430:2)
    at new ResponseMessage (/server/node_modules/net-snmp/index.js:537:14)
    at Session.onMsg (/server/node_modules/net-snmp/index.js:911:17)
    at Socket.emit (events.js:223:5)
    at UDP.onMessage [as onmessage] (dgram.js:874:8)

This throw doesn't float up.
I can't catch this error on my program code.

Thank you.

**Comment by markabrahams** [comment]
Hi @entcor - if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would be great. In particular these points:
- Reduce the problem to a minimal reproducible example
- Post code
- Include packet captures

**Comment by markabrahams** [comment]
This library no longer uses its own implementation of `readUint()` with the RangeError check.  It now calls the `asn1-ber` `readInt()` instead, which does not produce this error, and so this error does not exist any more.
