### ISSUE TITLE
getNext Unhandled 'error' event

### ISSUE THREAD

**Issue by ernestclyde** [markabrahams/node-net-snmp#171]
Good day
currently i am getting an error regarding Unhandled 'error' event this only happens where there are no oids found on a table, even handling the error on session.getNext ([oid], function (error, varbinds) {}) throws an error regarding:
`ResponseInvalidError: Unknown type '3' in response
    at readVarbindValue (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:465:9)
    at readVarbinds (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:484:15)
    at GetResponsePdu.SimpleResponsePdu.initializeFromBuffer (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:802:2)
    at Function.GetResponsePdu.createFromBuffer (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:820:6)
    at readPdu (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:861:24)
    at Function.Message.createFromBuffer (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:1606:17)
    at Session.onMsg (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:2056:25)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
Emitted 'error' event on Session instance at:
    at Session.onMsg (/home/myuser/scripts/limiter/node_modules/net-snmp/index.js:2058:8)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)`

**Comment by olishr** [comment]
Did you try something like

```
if (varbinds[i].type = 3) {
..do something with error
}
```

**Comment by ernestclyde** [comment]
Hello,
currently i modified the readVarbindValue function in index.js and added
`else if (type == 3) {
		buffer.readByte ();
		buffer.readByte ();
		value = null;
	}`
im am wondering why the type is not NoSuchObject when i am performing an intended get next for a oid that doesn't exist

**Comment by markabrahams** [comment]
Hi @ernestclyde - if you could follow the guidelines in CONTRIBUTING.md on what to include in a bug report - that would be great. In particular these points:
- Reduce the problem to a minimal reproducible example
- Post code
- Include packet captures

Also, include a snippet of the MIB you're querying that includes the `oid` parameter you're using in the `getNext` call (if the OID exists in the MIB), and the next OID that is being retrieved as a result of the `getNext` call.

**Comment by markabrahams** [comment]
ASN.1 type 3 is a bit string, and I've added support for reading these now and published this in version 3.8.1 of the npm.
