### ISSUE TITLE
Error: argument is not a valid OID string

### ISSUE THREAD

**Issue by SBits2019** [markabrahams/node-net-snmp#180]
I am trying to fetch HOST-RESOURCES Oid using `session.get`. (CPU/Mem usage for a particular process id).

http://www.oidview.com/mibs/0/HOST-RESOURCES-MIB.html

 It works from the terminal using `snmp get`

```
snmpget -v2c -c public 172.xx.xxx.xx 1.3.6.1.2.1.25.5.1.1.1.126184
SNMPv2-SMI::mib-2.25.5.1.1.1.126184 = INTEGER: 93391
```

hrSWRunPerfCPU | 1.3.6.1.2.1.25.5.1.1.1

hrSWRunPerfMem | 1.3.6.1.2.1.25.5.1.1.2

Here is my code snippet
```
const snmp = require('net-snmp');

const options = {
  version: snmp.Version2c, // version 2c gives 64 bit counters
};

const session = snmp.createSession(
  '172.xx.xx.xx', 
  'public',
  options,
);

const oid = '1.3.6.1.2.1.25.5.1.1.1.126184'; (the last number is the process id for the process)

session.get(oid, function(error, varbinds) {
  if (error) {
    console.error(error);
  } else {
    for (var i = 0; i < varbinds.length; i++)
      if (snmp.isVarbindError(varbinds[i]))
        console.error(snmp.varbindError(varbinds[i]));
      else console.log(varbinds[i].oid + ' = ' + varbinds[i].value);
  }
});
```
This is the error:

```
Error: argument is not a valid OID string
    at Writer.writeOID (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/asn1-ber/lib/ber/writer.js:181:9)
    at writeVarbinds (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/net-snmp/index.js:330:10)
    at GetRequestPdu.SimplePdu.toBuffer (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/net-snmp/index.js:399:2)
    at RequestMessage.toBuffer (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/net-snmp/index.js:517:11)
    at Session.send (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/net-snmp/index.js:985:28)
    at Session.simpleGet (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/net-snmp/index.js:1068:8)
    at Session.get (/home/pankaj/projects/systemmanagement/srv/worker/node_modules/net-snmp/index.js:657:7)
    at Object.<anonymous> (/home/pankaj/projects/systemmanagement/srv/worker/nsnmp.js:15:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Is there a way around this, I want to avoid walking the entire table if possible.

**Comment by markabrahams** [comment]
Hi @SBits2019 - if you check the README documentation for the `session.get` call, you'll see that the first argument is an array of OIDs, not a single OID string.
