### ISSUE TITLE
v3.14.0 MIB parser throws TypeError: Cannot read properties of undefined (reading 'TYPE NOTATION')

### ISSUE THREAD

**Issue by ddolcimascolo** [markabrahams/node-net-snmp#257]
Hi @markabrahams 

Thanks for your fix in https://github.com/markabrahams/node-net-snmp/issues/256  
Unfortunately, one of my unit test now fails with:

TypeError: Cannot read properties of undefined (reading 'TYPE NOTATION')
    at Object.Compile (/data/dev/cmdb/node_modules/net-snmp/lib/mib.js:405:67)
    at Object.Serialize (/data/dev/cmdb/node_modules/net-snmp/lib/mib.js:337:18)
    at ModuleStore.loadFromFile (/data/dev/cmdb/node_modules/net-snmp/index.js:3234:14)

This test uses the Dell MIB I'm talking about in https://github.com/markabrahams/node-net-snmp/issues/256

I'm setting up a reproduction repository and will edit this issue when done. 

Cheers,
David

**Comment by ddolcimascolo** [comment]
Reproduction repo: https://github.com/ddolcimascolo/net-snmp-issue-257

**Comment by ddolcimascolo** [comment]
Excellent! Thanks for the quick response and pardon my noobness regarding SNMP :)
I'll test v3.14.1 anfd report back here ASAP

David
