### ISSUE TITLE
AES 128: TypeError: Cannot read property 'encryptPdu' of undefined

### ISSUE THREAD

**Issue by dattatelite** [markabrahams/node-net-snmp#70]
This is an extension of issue #64 and feature update #57 (Version 2.5.0 - 25/01/2020).

Currently on the latest build Version 2.5.6 - 02/04/2020
There seems to be an issue with AES 128. The stack trace for the same is shown below:

TypeError: Cannot read property 'encryptPdu' of undefined
    at Object.Encryption.encryptPdu (*node_modules\net-snmp\index.js:918:60)
    at Message.toBufferV3 (*node_modules\net-snmp\index.js:1237:33)
    at Message.toBuffer (*node_modules\net-snmp\index.js:1135:15)
    at Session.send (*node_modules\net-snmp\index.js:2039:28)
    at Session.sendV3Req (*node_modules\net-snmp\index.js:2503:7)
    at Session.onMsg (*node_modules\net-snmp\index.js:1970:12)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage (dgram.js:659:8)

**Comment by dattatelite** [comment]
### What works in terms of the net-snmp binaries is:
```
snmpget -v 3 -n "" -u blinkybill2 -l authPriv -a MD5 -A somethingisbetterthannothing -x AES -X somethingisbetterthannothing 192.168.x.x 1.3.6.1.2.1.1.3.0
```
### My Code:
```
var options = {
    port: 161,
    retries: 1,
    timeout: 5000,
    transport: "udp4",
    trapPort: 162,
    version: snmp.Version3,
    idBitsSize: 32
  };

var userObj = {
    name: blinkybill2,
    level: snmp.SecurityLevel.authPriv,
    authProtocol: snmp.AuthProtocols.md5,
    authKey: "somethingisbetterthannothing",
    privProtocol: snmp.PrivProtocols.des,
    privKey: "somethingisbetterthannothing"
  };

let session = await snmp.createV3Session (192.168.x.x, userObj, options);
let oids = ["1.3.6.1.2.1.1.3.0"];
session.get (oids, function (error, varbinds) {
    if (error) {
      console.error (error.toString ());
    } else {
      for (var i = 0; i < varbinds.length; i++) {
        if (snmp.isVarbindError (varbinds[i]))
          console.error (snmp.varbindError (varbinds[i]));
        else
          console.log (varbinds[i].oid + "|" + varbinds[i].value);
      }
    }
  });
```

**Comment by markabrahams** [comment]
Hi @dattatelite - you have the privProtocol as DES instead of AES in your code - is that the issue?

**Comment by dattatelite** [comment]
> Hi @dattatelite - you have the privProtocol as DES instead of AES in your code - is that the issue?

Ah sorry, copied the wrong snippet on the comment. Updated it.

**Comment by gavinaiken** [comment]
What type of device are you seeing this error on? I am in the process of trying to test v3 support, mainly with AES encryption, against a variety of device types, and can try to replicate this if we have anything similar.

**Comment by markabrahams** [comment]
Yes end device type is important - I ran the supplied code with typos fixed (quotes around the user name) against the Net-SNMP agent and this succeeded ok.

**Comment by dattatelite** [comment]
The device is an APC Network Management card. 
(https://www.apc.com/shop/in/en/products/UPS-Network-Management-Card-3-with-Environmental-Monitoring/P-AP9641)

**Comment by dattatelite** [comment]
```
var snmp = require ("net-snmp");
function snmpv3ConnectNetSnmpModule(ipAddress, userName, authPrivSetting, authType, privType, authKey, privKey){
	var options = {
		port: 161,
		retries: 1,
		timeout: 5000,
		transport: "udp4",
		trapPort: 162,
		version: snmp.Version3,
		idBitsSize: 32
	  };
	var authPrivSettingTemp;
	if(authPrivSetting.toLowerCase() == "noauthnopriv"){authPrivSettingTemp = snmp.SecurityLevel.noAuthNoPriv}
	else if(authPrivSetting.toLowerCase() == "authnopriv"){authPrivSettingTemp = snmp.SecurityLevel.authNoPriv}
	else if(authPrivSetting.toLowerCase() == "authpriv"){authPrivSettingTemp = snmp.SecurityLevel.authPriv}
	else()=>{
		console.log("InvalidauthprivSetting")
		return "snmpOidGetFailed";
	}
	var authTypeTemp;
	if(authType.toLowerCase()  == "md5"){authTypeTemp = snmp.AuthProtocols.md5;}
	else if(authType.toLowerCase()  == "sha"){authTypeTemp = snmp.AuthProtocols.sha;}
	else()=>{
		console.log("Invalid authType")
		return "snmpOidGetFailed";
	}
	var privTypeTemp;
	if(privType.toLowerCase()  == "des"){privTypeTemp = snmp.PrivProtocols.des;}
	else if(privType.toLowerCase()  == "aes"){privTypeTemp = snmp.PrivProtocols.aes;}
	else()=>{
		console.log("Invalid privType")
		return "snmpOidGetFailed";
	}
	 
	var userObj = {
		name: userName,
		level: authPrivSettingTemp,
		authProtocol: authTypeTemp,
		authKey: authKey,
		privProtocol: privTypeTemp,
		privKey: privKey
	};
  

	var session = snmp.createV3Session (ipAddress, userObj, options);
	var oids = ["1.3.6.1.2.1.1.3.0"];
	session.get (oids, function (error, varbinds) {
		if (error) {
		  console.error (error.toString ());
		} else {
		  for (var i = 0; i < varbinds.length; i++) {
			if (snmp.isVarbindError (varbinds[i]))
			  console.error (snmp.varbindError (varbinds[i]));
			else
			  console.log (varbinds[i].oid + "|" + varbinds[i].value);
		  }
		}
	});
}
snmpv3ConnectNetSnmpModule("10.179.225.141", "blinkybill1", "authPriv", "MD5", "DES", "somethingisbetterthannothing", "somethingisbetterthannothing");
snmpv3ConnectNetSnmpModule("10.179.225.141", "blinkybill2", "authPriv", "SHA", "DES", "somethingisbetterthannothing", "somethingisbetterthannothing");
snmpv3ConnectNetSnmpModule("10.179.225.141", "blinkybill3", "authPriv", "MD5", "AES", "somethingisbetterthannothing", "somethingisbetterthannothing");
snmpv3ConnectNetSnmpModule("10.179.225.141", "blinkybill4", "authPriv", "SHA", "AES", "somethingisbetterthannothing", "somethingisbetterthannothing");

```

**Comment by dattatelite** [comment]
I checked this with 2 devices. I only saw the issue with them. The rest of the devices are working well.
After a format on the older devices. It seems to work as well. 
Making the issue is invalid. 
(closing)
Thanks again.

**Comment by markabrahams** [comment]
@dattatelite - thanks for posting your findings and rounding this off - much appreciated.

**Comment by gavinaiken** [comment]
We have some APC PDUs which we monitor with v2c at the moment. Will try to get v3 set up on them and test them some time soon.
