### ISSUE TITLE
Subagent oid issue

### ISSUE THREAD

**Issue by pluzzke** [markabrahams/node-net-snmp#98]
with the current code when i add a oid it will always add a .0 to the end. This oke however whenyou do an snmp get without the trailing .0 the application will crash:
```
TypeError: Cannot read property 'provider' of null
    at Subagent.request (node_modules\net-snmp\index.js:4920:27)
    at Subagent.getRequest node_modules\net-snmp\index.js:5019:7)
    at Subagent.onMsg (node_modules\net-snmp\index.js:4820:9)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) Uncaught Exception thrown
```

It looks like the instanceNode collected somehow also has a provider which it should not have. The providerNode = this.mib.getProviderNodeForInstance (instanceNode); function does not allow an instanceNode with a provider so the code will crash because the function returns null;

When it tried to fix this issue by simply adding this on line 4893 :
```
 if( instanceNode.provider){
        instanceNode = null;
 }
```

I get the following error:
```
ReferenceError: responsePdu is not defined
    at MibRequest.mibRequest.done (node_modules\net-snmp\index.js:4926:6)
    at getNsoHandler (node_modules\net-snmp\index.js:4903:22)
    at Subagent.request (node_modules\net-snmp\index.js:4967:4)
    at Subagent.getRequest (node_modules\net-snmp\index.js:5019:7)
    at Subagent.onMsg (node_modules\net-snmp\index.js:4820:9)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) Uncaught Exception thrown
```
Looking at the code the responsePdu object is never created but also never used inside of the function. Is this just a copy paste issue? Removing the two lines (4926,4927) also removes the issue

With these two fixes in place i now get an empty response form the oid. But it should ofcourse tell me there is no oid like this...

**Comment by markabrahams** [comment]
Hi @pluzzke - thanks for reporting this.  I've fixed this in master now and published the fix in version 2.7.1 of the npm.
